language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install coverage requests
  - pip install -i https://test.pypi.org/simple/ pyrecard
script:
  - coverage run test_suite.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
